### Operations by List

In [15]:
# initialized the matrices using variables A, B, C
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Using python lists adding the matrices
def addition_using_list(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# Using python lists multiplying the matrices
def multiplication_using_list(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(len(B))) for j in range(len(B[0]))] for i in range(len(A))]

# Using python lists subtracting the matrices
def subtract_using_list(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

print("Matrix addition using list: ", addition_using_list(A,B))
print("Matrix subtraction using list: ", subtract_using_list(A,B))
print("Matrix multipication using list: ", multiplication_using_list(A,B))
print("\n\n\n")

#profile the operation by list
import cProfile
def profile_list_operations():
    addition_using_list(A, B)
    subtract_using_list(A, C)
    multiplication_using_list(A, B)

cProfile.run('profile_list_operations()')

Matrix addition using list:  [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
Matrix subtraction using list:  [[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]
Matrix multipication using list:  [[22.43066479, 26.852805330000002, 39.53569494], [18.73605675, 23.61065602, 38.8279668], [16.10897299, 20.754939779999997, 43.42603136]]




         73 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 755495116.py:11(multiplication_using_list)
       36    0.000    0.000    0.000    0.000 755495116.py:12(<genexpr>)
        1    0.000    0.000    0.000    0.000 755495116.py:15(subtract_using_list)
        1    0.000    0.000    0.000    0.000 755495116.py:25(profile_list_operations)
        1    0.00

## Operations by Numpy

In [21]:
import numpy as np

# initialize matrices using NumPy arrays
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Matrix Addition using numpy
def addition_using_np(A, B):
    return A + B

# Matrix Multiplication using numpy
def multiplication_using_np(A, B):
    return np.dot(A, B)

# Matrix Subtraction using numpy
def subtraction_using_np(A, B):
    return A - B

print("Matrix addition using np: ", addition_using_np(A,B))
print("Matrix subtraction using np: ", subtraction_using_np(A,B))
print("Matrix multipication using np: ", multiplication_using_np(A,B))
print("\n\n\n")

# Profile the oerations
import cProfile
def profile_numpy_operations():
    addition_using_np(A, B)
    multiplication_using_np(A, C)
    subtraction_using_np(A, B)

cProfile.run('profile_numpy_operations()')

Matrix addition using np:  [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]
Matrix subtraction using np:  [[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]
Matrix multipication using np:  [[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]




         8 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 2058556789.py:13(multiplication_using_np)
        1    0.000    0.000    0.000    0.000 2058556789.py:17(subtraction_using_np)
        1    0.000    0.000    0.000    0.000 2058556789.py:27(profile_numpy_operations)
        1    0.000    0.000    0.000    0.000 2058556789.py:9(addition_using_np)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 multiarray.py:741(dot)
        1